# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gxep',
                'doc_host': 'https://cjGO.github.io',
                'git_url': 'https://github.com/cjGO/gxep',
                'lib_path': 'gxep'},
  'syms': {'gxep.core': {'gxep.core.foo': ('core.html#foo', 'gxep/core.py')}}}
