"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_config.ipynb.

# %% auto 0
__all__ = ['root', 'marker_data_path', 'train_data_path', 'test_data_path', 'col_names']

# %% ../nbs/00_config.ipynb 4
from nbdev.config import get_config
from pathlib import Path

# 1. Get the project root directory (the folder containing settings.ini)
# In your case, this correctly resolves to '/home/glect/gdrive/gxep'
root = get_config().config_path

# 2. Define all your data paths relative to that root
marker_data_path = root/'data'/'GenomicMarkers.csv'
train_data_path = root/'data'/'TrainingData.csv'
test_data_path = root/'data'/'TestData.csv'
print(marker_data_path)

col_names = ['genotype.id','replicate','tillering','leaf.size','maturity','plant.density','environment','yield']

#fold_config

