"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_data.ipynb.

# %% auto 0
__all__ = ['marker', 'train', 'test', 'load_data']

# %% ../nbs/02_data.ipynb 4
import numpy as np
import pandas as pd
from .config import *

def load_data():
    #load csv from marker_data_path
    marker = pd.read_csv(marker_data_path)
    #load csv from training_data_path
    train = pd.read_csv(train_data_path)
    test = pd.read_csv(test_data_path)
    return marker, train, test

marker, train, test = load_data()

