"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_features.ipynb.

# %% auto 0
__all__ = ['calculate_grm_vanraden']

# %% ../nbs/03_features.ipynb 3
import numpy as np
import pandas as pd # Import the pandas library

def calculate_grm_vanraden(genotype_matrix: np.ndarray) -> np.ndarray:
    """
    Calculates the Genomic Relationship Matrix (GRM) using VanRaden's method 1.
    """
    # Get matrix dimensions: n = number of individuals, m = number of markers.
    n, m = genotype_matrix.shape
    
    print(f"🧬 Analyzing {n} individuals and {m} markers...")

    # Step 1: Calculate allele frequencies (p)
    p = np.sum(genotype_matrix, axis=0) / (2 * n)
    
    # Step 2: Center the genotype matrix to create matrix M
    M = genotype_matrix - (2 * p)
    
    # Step 3: Calculate the scaling factor
    denominator = 2 * np.sum(p * (1 - p))
    
    # Step 4: Compute the GRM (G)
    G = (M @ M.T) / denominator
    
    print("✅ GRM calculation complete.")
    return G
